import { Template01 } from "./Template01";
import { Template02 } from "./Template02";
import { Template03 } from "./Template03";
import { Template04 } from "./Template04";
import { Template05 } from "./Template05";
import { Template06 } from "./Template06";
import { Template07 } from "./Template07";
import { Template08 } from "./Template08";
import { Template09 } from "./Template09";
import { Template10 } from "./Template10";
import { Template11 } from "./Template11";
import { Template12 } from "./Template12";
import { Template13 } from "./Template13";
import { Template15 } from "./Template15";
import { Template16 } from "./Template16";
import { Template17 } from "./Template17";
import { Template18 } from "./Template18";
import { Template19 } from "./Template19";
import { Template20 } from "./Template20";
import { Template21 } from "./Template21";

const TEMPLATE_REGISTRY = {
  101: Template01,
  102: Template02,
  103: Template03,
  // from here all the templates are new and generated by AI (Claude & GPT4)
  104: Template04,
  105: Template05,
  106: Template06,
  107: Template07,
  108: Template08,
  109: Template09,
  110: Template10,
  111: Template11,
  112: Template12,
  113: Template13,
  115: Template15,
  116: Template16,
  117: Template17,
  118: Template18,
  119: Template19,
  120: Template20,
  121: Template21,
};

// generates template on selected templates
export const generatePDF = ({ formData }) => {
  const selected_template = formData.selected_template || 101;

  const templateGenerator = TEMPLATE_REGISTRY[selected_template];

  if (!templateGenerator) {
    console.error(`Template ${selected_template} not found`);
    throw new Error(`Template ${selected_template} is not implemented`);
  }

  return templateGenerator({ formData });
};

export const devTemplate = {
  id: 117,
  image: `https://res.cloudinary.com/dartdvch1/image/upload/v1777304303/27-04-2026_page-0001_hugz2g.jpg`,
};

// templates are stored in cloudinary
export const templateImgs = [
  {
    id: 106,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1773830381/wsdtd_page-0001_le27ky.jpg`,
  },
  {
    id: 107,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1773830490/wv0rt_page-0001_m9zl2z.jpg`,
  },

  {
    id: 109,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1773830560/ww8eo_page-0001_kizhls.jpg`,
  },
  {
    id: 115,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1773830650/wyfmr_page-0001_gi8eyz.jpg`,
  },
  {
    id: 118,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1773830740/x0j1x_page-0001_ruemop.jpg`,
  },
  {
    id: 119,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1773830794/x1i6h_page-0001_c5qwrs.jpg`,
  },
  {
    id: 121,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1773830895/x3pn0_page-0001_rckwfj.jpg`,
  },
];
