import { Template01 } from "./Template01";
import { Template02 } from "./Template02";
import { Template03 } from "./Template03";
import { Template04 } from "./Template04";
import { Template05 } from "./Template05";
import { Template06 } from "./Template06";
import { Template07 } from "./Template07";
import { Template08 } from "./Template08";
import { Template09 } from "./Template09";
import { Template10 } from "./Template10";
import { Template11 } from "./Template11";
import { Template12 } from "./Template12";
import { Template13 } from "./Template13";
import { Template15 } from "./Template15";
import { Template16 } from "./Template16";
import { Template17 } from "./Template17";

const TEMPLATE_REGISTRY = {
  101: Template01,
  102: Template02,
  103: Template03,
  // from here all the templates are new and generated by AI (Claude & GPT4) 
  104: Template04,
  105: Template05,
  106: Template06,
  107: Template07,
  108: Template08,
  109: Template09,
  110: Template10,
  111: Template11,
  112: Template12,
  113: Template13,
  115: Template15,
  116: Template16,
  117: Template17
};

// generates template on selected templates
export const generatePDF = ({ formData }) => {
  const selected_template = formData.selected_template || 101;

  const templateGenerator = TEMPLATE_REGISTRY[selected_template];

  if (!templateGenerator) {
    console.error(`Template ${selected_template} not found`);
    throw new Error(`Template ${selected_template} is not implemented`);
  }

  return templateGenerator({ formData });
};

export const devTemplate = {
  id: 117,
  image: `https://res.cloudinary.com/dartdvch1/image/upload/v1752485028/wbice_page-0001_vijpwg.jpg`,
};


// templates are stored in cloudinary
export const templateImgs = [
  {
    id: 101,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1746337100/Template_01_page-0001_euwkh8.jpg`,
  },
  {
    id: 102,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1746337099/Template_02_page-0001_dc788l.jpg`,
  },
  {
    id: 103,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1746337100/Template_03_page-0001_enli5c.jpg`,
  },
  {
    id: 104,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1751364481/template4_page-0001_ux8fxx.jpg`,
  },
  {
    id: 105,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1751364791/template5_page-0001_zra0kl.jpg`,
  },
  {
    id: 106,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1751364480/template6_page-0001_uwa6f9.jpg`,
  },
  {
    id: 107,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1751364791/template7_page-0001_hmwryb.jpg`,
  },
  {
    id: 108,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1751365012/template8_page-0001_x2fkii.jpg`,
  },

  {
    id: 109,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1751364331/Temaplate9_page-0001_quahye.jpg`,
  },
  {
    id: 110,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1751364331/template10_page-0001_ix5okb.jpg`,
  },
  {
    id: 111,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1751365012/template11_page-0001_i6etpm.jpg`,
  },
  {
    id: 112,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1751364330/Template12_page-0001_ho4ccc.jpg`,
  },
  {
    id: 113,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1751366592/Template13_page-0001_a3azmv.jpg`,
  },
  {
    id: 115,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1751369183/fy71d_page-0001_wjcvja.jpg`,
  },
  {
    id: 116,
    image: `https://res.cloudinary.com/dartdvch1/image/upload/v1751370803/template16_page-0001_rtpyfx.jpg`,
  },
];
